### ISSUE TITLE
wheel contains python2.7 .pyc files

### ISSUE THREAD

**Issue by asottile** [warner/python-ecdsa#106]
This is usually not a problem, but when attempting to use `virtualenv-tools3` to relocate a virtualenv this crash occurs.  I can provide a patch to ~hopefully fix / prevent this in the future -- a similar patch was needed for pycparser:

```console
$ unzip ../*.whl
Archive:  ../ecdsa-0.13-py2.py3-none-any.whl
  inflating: ecdsa/__init__.py       
  inflating: ecdsa/__init__.pyc      
  inflating: ecdsa/_version.py       
  inflating: ecdsa/_version.pyc      
  inflating: ecdsa/curves.py         
  inflating: ecdsa/curves.pyc        
  inflating: ecdsa/der.py            
  inflating: ecdsa/der.pyc           
  inflating: ecdsa/ecdsa.py          
  inflating: ecdsa/ecdsa.pyc         
  inflating: ecdsa/ellipticcurve.py  
  inflating: ecdsa/ellipticcurve.pyc  
  inflating: ecdsa/keys.py           
  inflating: ecdsa/keys.pyc          
  inflating: ecdsa/numbertheory.py   
  inflating: ecdsa/numbertheory.pyc  
  inflating: ecdsa/rfc6979.py        
  inflating: ecdsa/rfc6979.pyc       
  inflating: ecdsa/six.py            
  inflating: ecdsa/six.pyc           
  inflating: ecdsa/test_pyecdsa.py   
  inflating: ecdsa/util.py           
  inflating: ecdsa/util.pyc          
  inflating: ecdsa-0.13.dist-info/DESCRIPTION.rst  
  inflating: ecdsa-0.13.dist-info/metadata.json  
  inflating: ecdsa-0.13.dist-info/top_level.txt  
  inflating: ecdsa-0.13.dist-info/WHEEL  
  inflating: ecdsa-0.13.dist-info/METADATA  
  inflating: ecdsa-0.13.dist-info/RECORD  
$ file ecdsa/curves.pyc
ecdsa/curves.pyc: python 2.7 byte-compiled
```

Here's the crash that one gets using `virtualenv-tools3`

```console
$ ./venv/bin/virtualenv-tools venv --update-path $PWD/venv4
Error in venv/lib/python3.6/site-packages/ecdsa/ecdsa.pyc
Traceback (most recent call last):
  File "./venv/bin/virtualenv-tools", line 10, in <module>
    sys.exit(main())
  File "/tmp/t/venv/lib/python3.6/site-packages/virtualenv_tools.py", line 349, in main
    update_paths(venv, update_path)
  File "/tmp/t/venv/lib/python3.6/site-packages/virtualenv_tools.py", line 224, in update_paths
    update_pycs(lib_dir, new_path)
  File "/tmp/t/venv/lib/python3.6/site-packages/virtualenv_tools.py", line 174, in update_pycs
    update_pyc(filename, local_path)
  File "/tmp/t/venv/lib/python3.6/site-packages/virtualenv_tools.py", line 121, in update_pyc
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by asottile** [comment]
I rebuilt a wheel against master and wasn't able to reproduce this -- I suspect it's an artifact from very old versions of wheel / setuptools that were used to build this package way back when

A simple re-release should resolve this issue I think

**Comment by tomato42** [comment]
patch would be definitely welcome

but to be completely honest, I don't have any experience with wheel files, so if you could give me also some references to official documentation of what are the expected contents of wheel files, it would make the review much faster

(side note: next release I planned was [0.14](https://github.com/warner/python-ecdsa/milestone/1) and it's still some way off... If you'd like to see a fix for this quickly, we'd need a 0.13 devel branch and push any changes as a 0.13.1 with just that one patch)

**Comment by asottile** [comment]
sweet, it looks like even building against the tagged release works as well (as long as setuptools / wheel are sufficiently new)

I can try and reproduce the old behaviour by downgrading things and then set up some minimum version checking as a patch to prevent this in the future :+1:

**Comment by asottile** [comment]
ok I've reproduced / pinpointed the problem.

It appears this can only be reproduced by running `compileall` during source distribution setup (which isn't a normal process) -- I don't think there's anything that can be done to protect against this and a trivial version bump to 0.13.1 should resolve this for me :+1: 

These are the commands I ran to break this:

```
python setup.py bdist_wheel  # produces the correct wheel, and a `./build` directory
python -m compileall .  # accidentally compiles pyc files inside the build directory
python setup.py bdist_wheel  # builds a wheel from the build directory without re-copying things as it appears "up to date" -- this causes the pyc files in the wheel
```

**Comment by asottile** [comment]
Oh and a command that can validate that the wheel is "correct" before uploading:

```bash
# should return nothing
unzip -l dist/*.whl | grep pyc$
```

**Comment by tomato42** [comment]
0.13.1 released with fixed wheel file, please check if it helps for virtualenv crash

**Comment by asottile** [comment]
Thanks a ton @tomato42 , this helps us a ton! :tada: 

Confirming the fix as well and closing this out o7
