### ISSUE TITLE
Explicitly re-use nonce (Fault attack demonstration)

### ISSUE THREAD

**Issue by 766F6964** [warner/python-ecdsa#112]
I have two different messages _m1_ and _m2_. I want to sign both messages and explicitly re-use the same nonce, preferably a value that I can choose myself. 

The idea is demonstrate a fault attack against ECDSA. For more information check [this paper](https://cybermashup.files.wordpress.com/2017/10/practical-fault-attack-against-eddsa_fdtc-2017.pdf).
Can you maybe provide a basic example how to do that? Because normally one should not be able to choose a nonce themselves for security reasons.

**Comment by tomato42** [comment]
pass the same value as random_k to this method:
https://github.com/warner/python-ecdsa/blob/72621b15a7c37f2c7cb7f11a2bc8feaac68b3914/src/ecdsa/ecdsa.py#L156

**Comment by gianlucafrei** [comment]
The paper you mentioned is about EdDSA which is not the same as EcDSA.  This repo only implements EcDsa. But EcDSA is also not secure of a nonce is reused. Make sure to not confuse the two different signing algorithms.

**Comment by 766F6964** [comment]
Thanks for the fast reply. However I am still having trouble signing a message when explicitly specifying the nonce. Please see the following example:

```python
from ecdsa import SigningKey

# Messages to sign
message1 = "Hello, this is a message"
message2 = "Hello, this is another message"

# Generate a public private keypair
sk = SigningKey.generate()
vk = sk.get_verifying_key()

# Attempt to sign both message and reuse the same nonce
signature1 = sk.sign(bytes(message1, encoding='utf-8'), 12345678)
signature2 = sk.sign(bytes(message2, encoding='utf-8'), 12345678)

# Print generated signatures
print("Signature message 1", signature1)
print("Signature message 2", signature2)
```
Results in the following exception:
```
Traceback (most recent call last):
  File "generate.py", line 12, in <module>
    signature1 = sk.sign(bytes(message1, encoding='utf-8'), 12345678)
  File "/usr/lib/python3.7/site-packages/ecdsa/keys.py", line 255, in sign
    return self.sign_digest(h, entropy, sigencode, k)
  File "/usr/lib/python3.7/site-packages/ecdsa/keys.py", line 263, in sign_digest
    r, s = self.sign_number(number, entropy, k)
  File "/usr/lib/python3.7/site-packages/ecdsa/keys.py", line 279, in sign_number
    _k = randrange(order, entropy)
  File "/usr/lib/python3.7/site-packages/ecdsa/util.py", line 51, in randrange
    candidate = string_to_number(entropy(bytes)) + 1
TypeError: 'int' object is not callable
```

**Comment by tomato42** [comment]
you're using completely different method, I talked about `Private_key.sign()`, you're using `SigningKey.sign()`. The latter one uses a random-like object instead of literal integer

**Comment by tomato42** [comment]
Use PRNG from util class, see https://github.com/warner/python-ecdsa#entropy for usage
