### ISSUE TITLE
`six` library is still vendored in 0.14 wheel release

### ISSUE THREAD

**Issue by spulec** [warner/python-ecdsa#159]
For the most recent release (`0.14`), I am getting an error after installing the wheel.

```python
>>> import ecdsa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steve/.virtualenvs/pyqs2/lib/python2.7/site-packages/ecdsa/__init__.py", line 1, in <module>
    from .keys import SigningKey, VerifyingKey, BadSignatureError, BadDigestError,\
  File "/Users/steve/.virtualenvs/pyqs2/lib/python2.7/site-packages/ecdsa/keys.py", line 72, in <module>
    from . import ecdsa
  File "/Users/steve/.virtualenvs/pyqs2/lib/python2.7/site-packages/ecdsa/ecdsa.py", line 57, in <module>
    from . import ellipticcurve
  File "/Users/steve/.virtualenvs/pyqs2/lib/python2.7/site-packages/ecdsa/ellipticcurve.py", line 37, in <module>
    from six import python_2_unicode_compatible
ImportError: cannot import name python_2_unicode_compatible
```

If I install using without using the wheel (`pip install ecdsa==0.14 --no-binary :all:`), I can confirm this doesn't happen. When looking at the files that get installed, I can see that `six.py` is still bundled for the wheel, but not the source installation.

All of this was on Python 2.7.12. Let me know if I can provide any more information to help debug.

**Comment by tomato42** [comment]
yes, I indeed see `six.py` in `ecdsa-0.14-py2.py3-none-any.whl`, will need to fix it

**Comment by spulec** [comment]
Someday we will all live in a Python3 world and leave problems like this behind :)

**Comment by tomato42** [comment]
RHEL 7 is going to be supported till like 2027... I won't hold my breath for this particular "someday" :smile:

**Comment by tomato42** [comment]
0.14.1 shipped: https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.14.1
should fix this

**Comment by spulec** [comment]
Thanks for the quick fix! I can confirm it works.

Thanks for all of your work on this library!
