### ISSUE TITLE
unify formatting between modules

### ISSUE THREAD

**Issue by tomato42** [warner/python-ecdsa#171]
currently modules use formatting all over the place, some use two spaces, some use the standard 4 spaces

remove the `E111` and `E114` from `flake8` configuration in `tox.ini`, fix the issues indentified

(depends on #170 )

**Comment by hukkinj1** [comment]
How about running https://github.com/psf/black once, and enforcing it in CI?

**Comment by tomato42** [comment]
that could also be an option, two things:
1. I don't like the 88 char limit, I'd prefer to stick to 80 (those 8 chars do make a difference on side-by-side diffs)
2. I worry about  py2.6 compatibility, there are some new syntax things in py2.7 that are missing from py2.6

if there's no problem with those, then I have no issues using it and enforcing in CI

**Comment by hukkinj1** [comment]
Here's the PR https://github.com/warner/python-ecdsa/pull/186

> 1. I don't like the 88 char limit, I'd prefer to stick to 80 (those 8 chars do make a difference on side-by-side diffs)

I ran black with max line length set to 79, which is the flake8 default that was used in this project.

> 2. I worry about py2.6 compatibility, there are some new syntax things in py2.7 that are missing from py2.6

Py2.6 tests seem to all pass, so if we can trust them, then all should be good. Perhaps it could also be a good time to drop 2.6 (or all of python 2) support now that even 2.7 was EOL'd recently?
