### ISSUE TITLE
wrong rolen usage instead of qlen, but....

### ISSUE THREAD

**Issue by cslashm** [warner/python-ecdsa#192]
If i correctly understand RFC, there is an error here :
https://github.com/warner/python-ecdsa/blob/fa18c32f4b6cf80c763f8968ed7c48706922e226/src/ecdsa/rfc6979.py#L96

A comparison with _qlen_ should be done,  instead of with _rolen_ as per RFC specification.
```
 2.  While tlen < qlen, do the following:
              V = HMAC_K(V)
              T = T || V
```
and qlen 

For example if used with Stark curve with prime field equal to 0x0800000000000011000000000000000000000000000000000000000000000001, _qlen_ is 252 and _rolen_ is 256

As consequence the loop occurs twice with _rolen_, but only once with _qlen_. it doesn't change the first k value but the subsequent k change.

Nonetheless the RFC reference implementation use rlen...

**Comment by tomato42** [comment]
but `len` gives the size in bytes, not bits, the unit of `qlen` is bits the unit of `rolen` is bytes; comparing `len(t)` to `qlen` would mix up units.

**Comment by cslashm** [comment]
OK, that's a pb of unit mixeup of course. To try to be more clear:

in rfc tlen and qlen are in bits:
` qlen is the smallest integer  such that q is less than 2^qlen.  This is the size of the binary   representation of q without a sign bi`
and 
`The length of T (in bits) is    denoted tlen`

So The RFC operate in bits in its spec and the reference implementation operate on bytes and so that's my first point. 

So correct python code shoud be something like: `while len(t)*8 < qlen` to agree with spec

But what about refimpl? That's my second point.

I'm still investigate the code, maybe i'm wrong....maybe not

**Comment by tomato42** [comment]
I still don't get how you get different outputs... the generation of T has granularity of hash output length and `rolen` is rounded up

no idea about reference implementation, that's not one

finally, even if the `k` generated was different, it won't have less entropy and it's still deterministic, so that seems like a non-issue to me

**Comment by cslashm** [comment]
I found the bug, it does not related to the rolen/qlen. I made miss interpretation of the spec that direct me in the wrong way

But the bug exist, aor more exactly a py3/py2 incompatibility

the computation line 56 `rolen = (qlen + 7) / 8` leadin into float in python 32.
Thus for some internal float representation I guess,  the comparison line 96 report `32 as int < 32 as float` as `True` and thus one uneeded step occurs

line 56 should be replace by ` rolen = (qlen + 7) // 8`  for python3 or ` rolen = int((qlen + 7) / 8)` for keeping compatibility

I close this bug and repoen a correct one
