### ISSUE TITLE
Computation may be wrong  in python 3

### ISSUE THREAD

**Issue by cslashm** [warner/python-ecdsa#193]
here:
https://github.com/warner/python-ecdsa/blob/fa18c32f4b6cf80c763f8968ed7c48706922e226/src/ecdsa/rfc6979.py#L56

The line should be change in   `rolen = int((qlen + 7) / 8)`

Indeed in python3 `/` always return a float,  then line 96 the comparison
`len(t) < rolen`  may lead into some aberration such as `32<32` that return True. 

This is because of float encoding.

**Comment by tomato42** [comment]
ok, #194 should fix it

**Comment by cslashm** [comment]
yes :). I didn't remember `//` was python2 ok.
