### ISSUE TITLE
How to load a Signing key from a hex string for signing messages?

### ISSUE THREAD

**Issue by Portia-Lin** [warner/python-ecdsa#196]
The end of the description describes how to load a verifying key from a hex string from compressed format, output uncompressed. But. how to load a Signing key from a hex string from compressed format, output uncompressed? I want to sign a message with an existing signing key:

```
message = b"message"
sk = "4bedab565cf11dbfffb7feb3d9b358d5187c0a439d76be24a60697175b44b2bf"
sign = sk.sign(message)
```

But signing key in hex string :( And i want to use hex format. How to convert? It is possible?

**Comment by tomato42** [comment]
signing keys don't have a compressed format

different curves require different lengths of private keys, that's why some are shorter than others

**Comment by Portia-Lin** [comment]
I want to enter the generated signing key from hex format and then sign the message by this key.

**Comment by tomato42** [comment]
Then you can use `from_string` method of SigningKey: https://github.com/warner/python-ecdsa/blob/d2f787ecfe73b92c7db0b0b50f02a6ef9c999944/src/ecdsa/keys.py#L804-L828

together with the same `bytearray.fromhex` as in the README.md example
