### ISSUE TITLE
point+point addition

### ISSUE THREAD

**Issue by hamnaz** [warner/python-ecdsa#210]
pls someone can correct to get result
-----------------
from ecdsa.curves import SECP256k1
from ecdsa.ellipticcurve import Point
from ecdsa import keys, curves
import gmpy2

x1 = 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798
y1 = 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

S = Point(x1, y1)

S1 = S+S

print (S1)

**Comment by tomato42** [comment]
not sure what you're attempting to do, but if you want the coordinates of the resulting point, you'll have to call `x()` and `y()`, like so:
```
print(S1.x())
print(S1.y())
```

**Comment by hamnaz** [comment]
example work and result, pls correct above script for get result
https://gist.github.com/nlitsme/c9031c7b9bf6bb009e5a
thankx

**Comment by tomato42** [comment]
you mean, something like this?
```
from ecdsa.curves import SECP256k1
from ecdsa.ellipticcurve import Point

x1 = 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798
y1 = 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8

S = Point(SECP256k1.curve, x1, y1)

S1 = S+S

print((hex(S1.x()), hex(S1.y())))
```

**Comment by hamnaz** [comment]
yes, but you remove import gmpy2
will above script will use gmpy2 auto or need to call import gmpy2 ?

**Comment by tomato42** [comment]
yes, it will use gmpy2 when it's installed, irrespective if other modules load it

but if speed is what you're after, you should use `PointJacobi`, not `Point`; the difference is also specify Z=1 when initialising the object

**Comment by hamnaz** [comment]
an other thing is gmpy2 you use, but not for inverse calc, 2nd is multiprocess capabilities for refrence, where gmpy2 uses for inverse too and multiprocess import in above script setting will help to load big lists and multiprocess will done job more fast
https://github.com/Telariust/pollard-kangaroo/blob/master/pollard-kangaroo-multi.py

**Comment by tomato42** [comment]
> an other thing is gmpy2 you use, but not for inverse calc, 

no, the code does use gmpy2 for inverse modulo:
https://github.com/warner/python-ecdsa/blob/f27b20ff2a67c6b1afe473dd347c8da5c4017e34/src/ecdsa/numbertheory.py#L222-L229
https://github.com/warner/python-ecdsa/blob/f27b20ff2a67c6b1afe473dd347c8da5c4017e34/src/ecdsa/numbertheory.py#L21-L25

and I did recently verify that it does use a special case algorithm for the x^-1 power: https://github.com/warner/python-ecdsa/issues/204#issuecomment-699516264

> 2nd is multiprocess capabilities for refrence, where gmpy2 uses for inverse too and multiprocess import in above script setting will help to load big lists and multiprocess will done job more fast
> https://github.com/Telariust/pollard-kangaroo/blob/master/pollard-kangaroo-multi.py

I can imagine using multiprocessing to calculate scalar multiples with precomputed multiples, but without precomputation? No, I don't think the point-double&add algorithm is parallelizable...

**Comment by hamnaz** [comment]
prev i were useing fastecdsa lib in python script, now i tested with python-ecdsa, same speed work, how i could check if my script is useing gmpy2, or you know fastecdsa also useing gmpy2
both script same speed, or maybe more fast we need to use cupy( cuda work ) for these python script, have you ever experiance with cupy ?

**Comment by tomato42** [comment]
As far as I know, fastecdsa 1.7.5 is slower than python-ecdsa 0.15 and later: https://github.com/AntonKueltz/fastecdsa/issues/45. While fastecdsa doesn't use gmpy2 it does use libgmp, so in the end we both use the same arbitrary precision arithmetic library...

> both script same speed

that seems unlikely, I don't see any configuration in which python-ecdsa performance would be equal to fastecdsa performance... even without gmpy2 python-ecdsa 0.15 and later should be faster

> or maybe more fast we need to use cupy( cuda work ) for these python script, have you ever experiance with cupy ?

no, never used cupy, but it's compatible to numpy, not gmpy2; numpy is good for vector and matrix operations, gmpy2 is for arbitrary precision arithmetic, they target completely different problems

finally, I don't think running a single scalar multiplication with CUDA would be faster than on a CPU, I'd be surprised if the communication overhead wouldn't kill any performance improvements

now, you *could* use CUDA to perform multiple scalar multiplications at the same time, if you'd use Montgomery ladder for it, and Fermat's theorem for calculating inverses modulo, but you'd have to completely rewrite this library to do that—as this is a general-purpose ECC/ECDSA library, I'd consider addition of such code to it to be out of scope

**Comment by hamnaz** [comment]
can i send you email at warner@lothar.com for discus more ?

**Comment by tomato42** [comment]
1. it's not my email
2. I'm not interested in work for hire. 
   1. If this is security related: please see the [security](https://github.com/warner/python-ecdsa#security) section in README.md — python-ecdsa is a toy library
   2. If it is performance related, you're looking at wrong programming language. And I'm not interested in writing performance-critical C or C++ code
