### ISSUE TITLE
add script to produce benchmark/perf data

### ISSUE THREAD

**Issue by warner** [warner/python-ecdsa#30]
In README.md, I have a section named "Speed" that provides timing data for creating/signing/verifying with various curves. I should dig up the script I used to produce that and include a copy in the source tree, so `setup.py bench` will produce the same table on your local machine.

Also, we should add similar data for the recently-added secp256k1 curve.

**Comment by tomato42** [comment]
I'm not sure if it crypto++ implementation is necessary for comparing performance... `openssl speed` gives performance numbers of ecdsa too.
