### ISSUE TITLE
Some plan to support XaDES?

### ISSUE THREAD

**Issue by miltonlab** [warner/python-ecdsa#32]
Or other alternative to use the XADES format?

**Comment by VictorPacheco** [comment]
Hola Milton, al fin encontraron alguna solución para firmar con python? Estoy en busca de lo mismo. Saludos.

**Comment by tomato42** [comment]
IMHO XAdES is entirely out of scope for the library. XAdES just describes what is signed and how the signature is stored. Think "a new PEM format" or "support for PKCS#7" not "a new FIPS 186-3 standard".

**Comment by jurdin** [comment]
if they find some solution would be great to share, I also have the same problem

**Comment by tomato42** [comment]
"won't fix" for the above stated reason
