### ISSUE TITLE
ecdsa.__version__ returns UNKNOWN for pypi package

### ISSUE THREAD

**Issue by novocaine** [warner/python-ecdsa#38]
```
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ecdsa
>>> ecdsa.__version__
'UNKNOWN'
```
presumably there's some build step missing before submission to pypi..?

**Comment by warner** [comment]
The next version should fix that.. we've got Versioneer installed, which should handle version strings when you build from a tarball. I'll try to make the release soon.

**Comment by warner** [comment]
I just pushed 0.12 to pypi, so this should work now.
