### ISSUE TITLE
add Brainpool curves

### ISSUE THREAD

**Issue by warner** [warner/python-ecdsa#4]
Zooko points out that many folks don't like the NIST curves because they don't come with a proof of being generated randomly. The Brainpool curves do. http://cryptopp.svn.sourceforge.net/viewvc/cryptopp/trunk/c5/eccrypto.cpp?r1=441&r2=440&pathrev=441 and http://cryptopp.svn.sourceforge.net/viewvc/cryptopp/trunk/c5/oids.h?r1=441&r2=440&pathrev=441 are where Brainpool support was added to Crypto++.

If OpenSSL supports these curves (so we can do interop testing), I'm happy to add them to python-ecdsa.

**Comment by shrirang-bhate** [comment]
Hi, I just came across this thread looking for brainpool curve support and ended up patching the curves. (patch attached here, if somebody is still interested; still need to test a few things...)
[brainpool_r1.txt](https://github.com/warner/python-ecdsa/files/552767/brainpool_r1.txt)

**Comment by tomato42** [comment]
There definitely are people interested. And the patch looks good, only test cases are missing.

**Comment by tomato42** [comment]
fixed by #61
