### ISSUE TITLE
Python 3: SigningKey.to_string() return a bytes object instead of a string

### ISSUE THREAD

**Issue by tuxayo** [warner/python-ecdsa#56]
```
>>> import ecdsa
>>> type(ecdsa.SigningKey.generate().to_string())
<class 'bytes'>
```

Is this normal?

Example of how to get a string for someone that need to display a key:

```
>>> import codecs
>>> sk = ecdsa.SigningKey.generate().to_string()
>>> codecs.encode(sk, 'hex').decode("utf-8")  # maybe there is a simpler way
'5d9411d69b0286f51d5ef52300dcd02b617d843877c8a881'
```

**Comment by jkdf2** [comment]
I also wonder if this is expected or not?

**Comment by tomato42** [comment]
it's a binary blob so `bytes` is correct, if it would be a `str` object, it would have to be encoded - hex, base84, uuencode - some of those are not applicable to some transfer or storage methods while others are but require more space than necessary, so a method that gives you a binary blob that you can then encode yourself is preferable

even if its name is a bit counter-intuitive

**Comment by mohammadobaid1** [comment]
In python 3 you convert key into string by simply 
sk = SigningKey.generate(curve=SECP256k1)
 sk_string=(sk.to_string()).hex()
print(sk_string)

**Comment by tomato42** [comment]
The documentation should specify that the outputted format is expected to be `bytes()` on Py3 and binary `str()` on Py2.

**Comment by jomarip** [comment]
Running into this same issue currently in porting pybitcoin from python 2 to python 3.

**Comment by tomato42** [comment]
@jomarip I'm currently the main maintainer and my position on this issue hasn't changed – it needs to be documented, but the behaviour is as expected.

Changing it to output `str` on py3 would break code that already works with python-ecdsa on py3, so changing it now is too late.

**Comment by tomato42** [comment]
I have proposed a pull request that documents the expected behaviour of the VerifyingKey and SigningKey classes.

Please take a look: #117
