### ISSUE TITLE
Import key from hex

### ISSUE THREAD

**Issue by sreeh-000** [warner/python-ecdsa#58]
Hello, I know that I can import an ECDSA Key from PEM:<br>
`from ecdsa import SigningKey, SECP256k1 #secp256k1: the one bitcoin uses`
<br>`sk = SigningKey.from_pem("""-----BEGIN EC PRIVATE KEY-----
.............................
-----END EC PRIVATE KEY-----""")`<br>
But, how do I import a private key (or public key) from hex?
For example, a hex private key in secp256k1: <br>
0xDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEF

**Comment by Moustikitos** [comment]
hi, try this 
```python
>>> import binascii
>>> binascii.unhexlify('DEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEF')
b'\xde\xad\xbe\xef\xde\xad\xbe\xef\xde\xad\xbe\xef\xde\xad\xbe\xef\xde\xad\xbe\xef\xde\xad\xbe\xef\xde\xad\xbe\xef\xde\xad\xbe\xef'```

**Comment by mikuh** [comment]
SigningKey.from_string(bytes().fromhex(sk_string), curve=NIST256p)
