### ISSUE TITLE
how to import private key

### ISSUE THREAD

**Issue by asebak** [warner/python-ecdsa#62]
If I have a private key string generated from a different library/programming language how would I import it to python-ecdsa and to sign it?

**Comment by sylvainpelissier** [comment]
What is the format of your private key ?

**Comment by tomato42** [comment]
please generate a new key pair and post here both the public and private part, then we'll be able to verify if we're interpreting it correctly

**Comment by asebak** [comment]
Thanks for the responses, but I managed to figure it out, I needed to add the der encoded parameter as an argument.
