### ISSUE TITLE
Why signature always has the same lenght?

### ISSUE THREAD

**Issue by alexshavelev** [warner/python-ecdsa#64]
Hi. We generate NIST256p via lib and there is some question.
Why signature always has the same lang? In other languages not. Also for example you generate sign in other language and len > 64 bytes. In this case lib crashes

**Comment by tomato42** [comment]
This library just signs, it does not perform hashing. You need to first hash the data to be signed and then sign the hash. That also means, that if you want to sign using SHA-384 and P-256, you need to truncate the output of SHA-384 function according to relevant spec.
