### ISSUE TITLE
need help with maintenance

### ISSUE THREAD

**Issue by warner** [warner/python-ecdsa#68]
I'm not doing a great job maintaining this package: I'm horribly behind on landing PRs and responding to issues. I'm not using it for any of my work or personal projects, which doesn't help. And there are a surprisingly high number of downloads on pypi.. I think it might be a dependency of some JWT library that must be a dependency of something pretty popular, but I haven't done the legwork to figure out what. So it deserves better than what I'm giving it.

Could anyone lend a hand? I'd like to add two or three folks as "Contributors" who can review/land patches. Eventually I want to hand off ownership to someone else. Preferably folks who use it on a regular basis and have a sense of how/where it's being used downstream, so we can be sure to not break anything important to our userbase.

**Comment by tomato42** [comment]
I'm using it with [tlslite-ng](https://github.com/tomato42/tlslite-ng) and indirectly with [tlsfuzzer](https://github.com/tomato42/tlsfuzzer).

If you think I didn't do horrible job with the few comments here and there, I'm willing to help.

**Comment by tomato42** [comment]
[libraries.io](https://libraries.io/pypi/ecdsa) has more examples of projects that use `ecdsa`.

**Comment by tomato42** [comment]
Brian gave me the permissions to push commits to the git repo and packages to PyPI so I'll be able now to handle issues and pull requests.

I'd like to do a release this year with at least the outstanding PRs, and anything else that lands in between.

**Comment by warner** [comment]
@tomato42 thank you so much for helping out!
