### ISSUE TITLE
Issue with test execution

### ISSUE THREAD

**Issue by dvido** [warner/python-ecdsa#69]
Hello,

I want to include this package in a larger script that checks security issues. I'm having trouble with running it (stand-alone) - when I run python setup.py test I get the following output:
running test
running egg_info
writing dependency_links to src\ecdsa.egg-info\dependency_links.txt
writing src\ecdsa.egg-info\PKG-INFO
writing requirements to src\ecdsa.egg-info\requires.txt
writing top-level names to src\ecdsa.egg-info\top_level.txt
reading manifest file 'src\ecdsa.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ecdsa\_version.py'
writing manifest file 'src\ecdsa.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

What am I missing? Why aren't the tests running and what does the warning mean?
I'm using Python 3.5 on Windows 7.

Thank you

**Comment by tomato42** [comment]
there were bugs in configuration of test executors. Please install `tox` and run `tox -e coverage` on current (0d3d29e) master, it should be fixed there.
