### ISSUE TITLE
Loading veryfying key from pem or der always defaults to sha1 hash function

### ISSUE THREAD

**Issue by bar-bog** [warner/python-ecdsa#72]
Hi,
first I want to say that your package is great :) Helped me a lot while testing ecdsa on my device.
 I have noticed that when you read the verifying key from pem or der format you can't specify hashing function and it defaults to sha1. I think it would be great to have it as a parameter as public key does not specify it.
Maybe I could help you with contribution?

**Comment by tomato42** [comment]
the default hash function is a public field of the class:
https://github.com/warner/python-ecdsa/blob/0d3d29e9cbc002cae610974b7d934b9accd8134a/src/ecdsa/keys.py#L31

so you can change it after loading it from the file

that being said, both `from_string` and `from_public_point` accept the default hash function (the `hashfunc` parameter), so I don't see why `from_pem` and `from_der` couldn't be extended similarly
