### ISSUE TITLE
the best way to put 64 len string to 32 len string so it can produce public key 

### ISSUE THREAD

**Issue by fijako** [warner/python-ecdsa#73]
Hi guys,

I am following instructions on bitcoin site, how to create public wallet. First step is ofcourse to produce the public key with ecdsa.

in tutorial they use following private_key = '18E14A7B6A307F426A94F8114701E7C8E774E7F9A47E2C2035DB29A206321725'

and my python code is:

```
from ecdsa import SigningKey, SECP256k1


a = '18E14A7B6A307F426A94F8114701E7C8E774E7F9A47E2C2035DB29A206321725'


key = SigningKey.from_string(a, curve=SECP256k1)
pub_key = g.get_verifying_key()
```
I receive this error:
    assert len(string) == curve.baselen, (len(string), curve.baselen)
builtins.AssertionError: (64, 32)

How could i fix this?

Thank you very much!

**Comment by tomato42** [comment]
The key you have is hex-encoded. You need to convert it to binary bytes.

something like
```
key = bytearray.fromhex(a)
key = SigningKey.from_string(key, curve=SECP256k1)
```
should work

**Comment by fijako** [comment]
@tomato42 
You are correct. Thank you very much. All the best!
