### ISSUE TITLE
sk.sign() expects a bytes object?

### ISSUE THREAD

**Issue by pors** [warner/python-ecdsa#75]
The usage example in the README:

```
from ecdsa import SigningKey
sk = SigningKey.generate() # uses NIST192p
vk = sk.get_verifying_key()
signature = sk.sign("message")
assert vk.verify(signature, "message")
```

With python 3.5 this gives me:

```
in sign
    h = hashfunc(data).digest()
TypeError: Unicode-objects must be encoded before hashing
```

`signature = sk.sign("message".encode('utf-8'))` does work.

Is this expected behavior?

**Comment by tomato42** [comment]
yes, signature operations are defined for byte strings (on algorithm level), it's just that `str()` in python 2 is exactly the same as `bytes()`.

**Comment by pors** [comment]
OK, thanks for the speedy reply!
