### ISSUE TITLE
How do I get the public key of the signer?

### ISSUE THREAD

**Issue by devssh** [warner/python-ecdsa#76]
Can I explicitly display the public key so that I know who signed the message?
Currently, my solution feels like it is relying too much on the internals rather than an api for displaying the public key

publicKey = SigningKey.generate().get_verifying_key()
"".join(publicKey.to_pem().decode().split("\n")[1:-2])

**Comment by devssh** [comment]
I checked the vk.to_pem method to convert it to a pem file but is there a way to directly get the public key like the signature.hex()

**Comment by tomato42** [comment]
using `get_verifying_key()` is definitely correct, as you want the public key

but to compare the public key to some other value you need to know how that other value is encoded, for human verification `to_string()` should be sufficient (though you need to be mindful of the usually used SEC format, see #54)

given your second line:
```python
"".join(publicKey.to_pem().decode().split("\n")[1:-2])
```
It looks like you need Base64 encoding of the DER form, so something like this should work:
```python
import base64
base64.b64encode(public_key.to_der())
```
