### ISSUE TITLE
How to sign with data and private key.

### ISSUE THREAD

**Issue by narnikgamarnikus** [warner/python-ecdsa#77]
Hello.

In Go, there is a [library] (https://github.com/blockcypher/btcutils) that allows sign. But it takes 2 arguments, and yours - one.

I need the function to take 2 arguments, and I did not find any libraries in Python to do this.

Perhaps I'm in vain looking to you for this question, but perhaps you understand what I need.

**Comment by tomato42** [comment]
`sign()` is method of `Private_key` object
to create `Private_key` you have to provide the private key

so exactly which part is the problem?

**Comment by tomato42** [comment]
not a bug and no answer from requester, closing
