### ISSUE TITLE
SigningKey.sign() externally computed hash (no hashing on its own)

### ISSUE THREAD

**Issue by kk720801** [warner/python-ecdsa#88]
It seems to be lack of consequence between README.md and SigningKey.sign() documentation. In README.md:
_The hashfunc= argument to sk.sign() and vk.verify() is used to turn an arbitrary string into fixed-length digest, which is then turned into a number that ECDSA can sign, and both sign and verify must use the same approach. The default value is **hashlib.sha1**_

On the other hand help (SigningKey) says the hashfunc is by default None:
_sign(self, data, entropy=None, hashfunc=**None**,_ 

What is the reality? Is passing None to hashfunc really causes that no hash will be computed and data provided to sign() will be signed directly?

**Comment by tomato42** [comment]
that's because that parameter in `sign()` can be used to override:
https://github.com/warner/python-ecdsa/blob/ffe9a61390c76ff6f6636e29f26b45c900535aaf/src/ecdsa/keys.py#L259

the default parameter set in `generate()`:
https://github.com/warner/python-ecdsa/blob/ffe9a61390c76ff6f6636e29f26b45c900535aaf/src/ecdsa/keys.py#L126

**Comment by kk720801** [comment]
Thank you @tomato42 for your comment.
Still I wonder if sign() can be configured that no hash is computed on data provided and the data is signed directly? This is scenario when data provided is hash itself computed externally. In openssl it is possible using following commands:

```
#generate private key
openssl ecparam -name secp256k1 -genkey -out private.pem
#generate public key
openssl ec -in private.pem -pubout -out public.pem

# create message file
printf "thisismessage" > message.dat

#sign and verify
openssl pkeyutl -sign -inkey private.pem -in message.dat -out message.sig
openssl pkeyutl -verify -pubin -inkey public.pem -in message.dat -sigfile message.sig

# parse signature in DER format
openssl asn1parse -inform der -in message.sig

```
The content of message.dat is directly signed (and no hash of it). I would like verify such created signature by python script using ecdsa. Given the output of the last (openssl asn1parse) command which is like:

```
Signature Verified Successfully
-------------- SIGNATURE
    0:d=0  hl=2 l=  69 cons: SEQUENCE
    2:d=1  hl=2 l=  33 prim: INTEGER           :99B42D61D39F5C24B4B7916C44F4FCE0816E8AE56210EE40261222381685D703
   37:d=1  hl=2 l=  32 prim: INTEGER           :43C3992BD8540D52C18E6C39FD0411798872467DDD9DCF742538289DC51DF35E
```


I would expect following python script to verify the signature:

```
from ecdsa import SigningKey, VerifyingKey, SECP256k1

pub = VerifyingKey.from_pem(open("public.pem").read())
signature = bytes.fromhex('99B42D61D39F5C24B4B7916C44F4FCE0816E8AE56210EE40261222381685D70343C3992BD8540D52C18E6C39FD0411798872467DDD9DCF742538289DC51DF35E')
assert pub.verify(signature, "thisismessage".encode(), hashfunc=None)

```
but the assertion fails... I would appreciate your hints how to sign/verify without hashing...

**Comment by tomato42** [comment]
that's what `verify_digest()` and `sign_digest()` methods do

**Comment by kk720801** [comment]
thank you @tomato42 for the hint - it works great!
