### ISSUE TITLE
VerifyingKey has no attribute default_hashfunc

### ISSUE THREAD

**Issue by rsoeldner** [warner/python-ecdsa#89]
I receive an error when trying to verify a signature:
```
  File "/nix/store/6y0dcram1jil24ckidcpr34sw0qjzm19-python3.6-ecdsa-0.13/lib/python3.6/site-packages/ecdsa/keys.py", line 99, in verify
    hashfunc = hashfunc or self.default_hashfunc
AttributeError: 'VerifyingKey' object has no attribute 'default_hashfunc'
```

On this snippet,  `sender.verify(self._signature, dumps(self.header))` with `sender` being ` <class 'ecdsa.keys.VerifyingKey'>`

I'm sending this object over the network with `jsonpickle`, maybe this destroys inner structure ?

**Comment by tomato42** [comment]
no familiar with pickle, but that does look like the instance variables were not transferred by jsonpicke (or it doesn't like classes that will raise TypeError on `__init__`)

**Comment by rsoeldner** [comment]
@tomato42 I pasted the following code, is there a way to get this working ?

```  
   kpair = SigningKey.generate(curve=NIST384p)
   sig = kpair.sign(msg.encode())
        
   e = jsonpickle.encode(kpair.get_verifying_key())
   r = jsonpickle.decode(e)

   r.verify(sig, msg.encode())
```

**Comment by tomato42** [comment]
that's an issue in `jsonpickle`, with the `pickle` module, this operation works:

```python
import pickle
from ecdsa.keys import SigningKey
from ecdsa import NIST384p
kpair = SigningKey.generate(curve=NIST384p)
sig = kpair.sign(b'some string')

e = pickle.dumps(kpair.get_verifying_key())
r = pickle.loads(e)

r.verify(sig, b'some string')
```
