### ISSUE TITLE
Compatibility with SJCL

### ISSUE THREAD

**Issue by kajchang** [warner/python-ecdsa#91]
Hello, I wanted to sign messages in the browser with [SJCL](https://github.com/bitwiseshiftleft/sjcl) and verify them server-side with this module, but I can't seem to get it to work. The signatures don't match up even though the keys seem to.

Same public keys from same private key:

```javascript
var pair = sjcl.ecc.ecdsa.generateKeys(192);

console.log(sjcl.codec.hex.fromBits(pair.pub.get().x.concat(pair.pub.get().y));
"7231a824d62fd9f10f5cea2e88850ca6ec5a99bbfafde598343e8b3e6b78c3dd5ea5e7e662304e4f114cdc68ede4586c"

console.log(sjcl.codec.hex.fromBits(pair.sec.get()));
"12073ad744124c8a82a93438ea04a98d5b7adbd72c3e69bf"
```

```python
sec = SigningKey.from_string(bytes.fromhex("12073ad744124c8a82a93438ea04a98d5b7adbd72c3e69bf"))
print(sec.get_verifying_key().to_string().hex())
"7231a824d62fd9f10f5cea2e88850ca6ec5a99bbfafde598343e8b3e6b78c3dd5ea5e7e662304e4f114cdc68ede4586c"
```

Signing:

```javascript
console.log(sjcl.codec.hex.fromBits(pair.sec.sign(sjcl.hash.sha1.hash('Example'))));
"a56b946e82ca0f84965d7bf9b958b030cdbed322f4eda31440eaf12df129892bb2dd77075714724dab270a80696c96af"
```

```python
print(sec.sign('Example'.encode()).hex())
"467facf9abe5124492814dec7c47ce8a1a4efde6edb1120f656eda4ef3f594f604e3f794690cca9db2392664703f658b"
```

I tried just passing 'Example' without using sha1 before sign for JS, but it didn't work either. How should I resolve this? Thanks!

**Comment by tomato42** [comment]
ECDSA signatures are non-determinisitc unless [RFC 6979](https://tools.ietf.org/html/rfc6979) algorithm is used.

Retry signatures with python-ecdsa multiple times and you'll see the signatures are different every time. That doesn't mean they can't be verified as correct.

**Comment by kajchang** [comment]
Thanks for the information and help!
